### ISSUE TITLE
loop test fails sometimes on s390x

### ISSUE THREAD

**Issue by chrissie-c** [ClusterLabs/libqb#478]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000003ffab98baba in qb_loop_timer_expire_time_remaining () from /lib64/libqb.so.100
Missing separate debuginfos, use: dnf debuginfo-install libqb-2.0.6-2.el9_1.s390x
(gdb) bt
#0  0x000003ffab98baba in qb_loop_timer_expire_time_remaining () from /lib64/libqb.so.100
#1  0x00000000010015fc in check_time_left (data=0x18d82a0) at cc-checkloop.c:191
#2  0x000003ffab988e00 in timer_dispatch () from /lib64/libqb.so.100
#3  0x000003ffab99070a in qb_loop_run () from /lib64/libqb.so.100
#4  0x0000000001001a48 in _fini ()
#5  0x000003ffe60fe518 in ?? ()

**Comment by chrissie-c** [comment]
Fixed in e038f59c52efac1e636d49e8b19c8299a4b31dde
